### PR TITLE
Added `fail_on_nodata` attribute to the cmci_get task

### PR DESCRIPTION
**Pull request by AndrewTwydell**
##### SUMMARY
Adds the `fail_on_nodata` attribute (True by default) to the cmci_get task that prevents the ansible task from failing if no data is returned from CMCI. 

Currently the CPSM response code received by ansible is 1027 when no records are present, which is considered an error by the cmci_get task. Setting the `fail_on_nodata` attribute to False prevents the ansible task from failing and returns the successful response, just with no records. 

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
Fail_on_nodata cmci_get feature

##### ADDITIONAL INFORMATION

Setting the new attribute:

```yaml
tasks:
    - name: Check CSD Already Exists
      cmci_get:
        context: "{{ context }}"
        scope: "{{ scope }}"
        cmci_host: "{{ cmci_host }}"
        cmci_port: "{{ cmci_port | int }}"
        cmci_user: "{{ cmci_user | default(omit) }}"
        cmci_password: "{{ cmci_password | default(omit) }}"
        scheme: "{{ scheme }}"
        type: CICSCSDGroup
        resources:
          filter:
            name: "{{ csdgroup }}"
        record_count: 1
        fail_on_nodata: "false"
```

###### Previous Output

```
fatal: [localhost]: FAILED! => 
    {"changed": false, "connect_version": "0610", "cpsm_reason": "", "cpsm_reason_code": 0, "cpsm_response": "NODATA", "cpsm_response_code": 1027, "http_status": "OK", "http_status_code": 200, "msg": "CMCI request failed with response \"NODATA\" reason \"1027\"", "record_count": 0, "request": {"body": null, "method": "GET", "url": "..."}}
```

###### Updated Output with Added Feature

```
ok: [localhost] => {
    "{'changed': False, 'request': {'url': '...', 'method': 'GET', 'body': None}, 'http_status_code': 200, 'http_status': 'OK', 'connect_version': '0610', 'cpsm_response': 'NODATA', 'cpsm_response_code': 1027, 'cpsm_reason': '', 'cpsm_reason_code': 0, 'record_count': 0, 'failed': False}"
}
```

### CODE REVIEW

**Review by tjlatham — COMMENTED** [review]
Looks good - once you've added an integration test for the new option I'll approve

**Comment by AndrewTwydell** [comment]
Integration tests added for `fail_on_nodata`:
  - Tests default bahaviour of failing the ansible task still occurs if the attribute is not set
  - Tests ansibile task passes if fail_on_nodata is False, and no records are returned

Test also added to ensure record_count attribute is used:
  - Retrieves multiple program definitions and checks for record count of 2
  - Retrieves same set of records with record_count attribute set, and ensures only 1 is returned

Added flexibility for integration testing, with no hard-coded region names embedded in the test files.

**Review by Tom-Latham — COMMENTED** [review]
Looks good thanks for doing the refactor too! Could you change 'cmci_scope_alternate_1/2' to 'cmci_scope_region_1/2'  please? I that'd be a little clearer

**Comment by AndrewTwydell** [comment]
> Looks good thanks for doing the refactor too! Could you change 'cmci_scope_alternate_1/2' to 'cmci_scope_region_1/2' please? I that'd be a little clearer

All done @Tom-Latham 👍🏼

**Review by Tom-Latham — APPROVED** [review]

**Pull request merged**
