### PR TITLE
Feature/1972/cics cmci

### PR DESCRIPTION
**Pull request by xiaoping8385**
##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by xiaoping8385** [comment]
Exception: ansible-test detected errors! 
 ERROR: Found 1 line-endings issue(s) which need to be resolved:
ERROR: docs/make.bat:0:0: use "\n" for line endings instead of "\r\n"
ERROR: Found 10 no-smart-quotes issue(s) which need to be resolved:
ERROR: docs/build/html/index.html:181:26: use ASCII quotes `'` and `"` instead of Unicode quotes
ERROR: docs/build/html/installation.html:336:66: use ASCII quotes `'` and `"` instead of Unicode quotes
ERROR: docs/build/html/modules/cics_cmci.html:255:38: use ASCII quotes `'` and `"` instead of Unicode quotes
ERROR: docs/build/html/modules/cics_cmci.html:286:44: use ASCII quotes `'` and `"` instead of Unicode quotes
ERROR: docs/build/html/modules/cics_cmci.html:308:40: use ASCII quotes `'` and `"` instead of Unicode quotes
ERROR: docs/build/html/playbooks.html:293:44: use ASCII quotes `'` and `"` instead of Unicode quotes
ERROR: docs/build/html/playbooks.html:298:5: use ASCII quotes `'` and `"` instead of Unicode quotes
ERROR: docs/build/html/playbooks.html:311:22: use ASCII quotes `'` and `"` instead of Unicode quotes
ERROR: docs/build/html/playbooks.html:319:68: use ASCII quotes `'` and `"` instead of Unicode quotes
ERROR: docs/build/html/playbooks.html:321:53: use ASCII quotes `'` and `"` instead of Unicode quotes
ERROR: Found 2 pep8 issue(s) which need to be resolved:
ERROR: docs/source/conf.py:34:1: E122: continuation line missing indentation or outdented
ERROR: docs/source/conf.py:51:1: E265: block comment should start with '# '
ERROR: Found 1 shebang issue(s) which need to be resolved:
ERROR: docs/build/html/_static/css/badge_only.css:0:0: file starts with a UTF-8 byte order mark
ERROR: The 4 sanity test(s) listed below (out of 41) failed. See error output above for details.

**Comment by xiaoping8385** [comment]
Exception: YAMLLint detected warnings and/or errors! 
 ./playbooks/cics-collection-sample-delete-resource.yml
  163:1     error    too many blank lines (1 > 0)  (empty-lines)

**Comment by xiaoping8385** [comment]
Exception: YAMLLint detected warnings and/or errors! 
 ./playbooks/cics-collection-sample-delete-resource.yml
  163:1     error    too many blank lines (1 > 0)  (empty-lines)

**Comment by stewartfrancis** [comment]
We have this feature into main already via GHE

**Comment by xiaoping8385** [comment]
Exception: hudson.AbortException: Fail: the returned code 404 is not in the accepted range: [[100‥399]]

**Pull request closed without merging**
